language: php
dist: trusty
matrix:
  include:
    - php: 5.3
      dist: precise
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
before_install:
- composer self-update
- composer clear-cache
install:
- travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest
  --optimize-autoloader --prefer-stable
script:
- "./vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=report.xml"
- sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  on_success: never
  on_failure: always
addons:
  sonarcloud:
    organization: "override2k"
    token:
      secure: U+tKq44ty7jLTZzW9V1Pjum4pmd4yk0ztiASgGOA74vRBGCEhJWeduBIH5S9HEzcL+sJozORIjEUFVaycLvaGdKM0pkFRhzSkNW2OzypACFRVZYoDjt1A9AG6ZVo9FvZDSIr475sNhuPIM5B+BvCMV7L14GXyaS/gmvh+Vvb8ho8iasRoVSqF8WiuyO8pBzqV/5p/IC2U8Z/TnsGJODaTZsuEcUh9dfQMbkslke7yBdw24R3XDtB4Q82T6Ox24pSgZAGyj+V97PtH8YZyASjMUX8PSslSvSSP7tYo/FTab21etZ919njT4vtzBJw51DVVHRqSRljuzvTH+Jr+JU/1EaFmtCmoQzx40FEgLENgR7LrrdozScxf2oPub/1fOvoWY3PpHIDHn0ZVlVzkwWw529mdnuihlEElg3a7ShXRgNfAbXziQ5Q7Cf1WksZVVX7/9PNSdTWIs4zLmipQu9DiXyuFHWNlaCyAkeU8jWaoHAGf+tWlB67MZXfugbGJDpghaDeBycfDkkJ6ZvcYL//gvxu/xI8VslFJzzblNNmaUBKhvBEnylPNi+vRpm/IPKg1Q3ytFIFwOmiQQ6U2rR7lyyiWv+DGzIgVqB7hZxLRpPJfJcFny6n1q1aIA0qr0RO910IajqTdkG/eGfqFqUtPidsxkpQqmYuLClkGmiUBeQ=
